In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://media.geeksforgeeks.org/wp-content/uploads/nba.csv')
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.dropna(subset=['Height', 'Weight'], inplace=True)

In [ ]:
def convertWeight(x):
  return x * 0.453592

In [ ]:
def convertHeight(x):
  foot = int(x.split('-')[0])
  inch = int(x.split('-')[1])
  return ((foot*12) + inch) * 0.0254 # convertendo tudo para metros

In [ ]:
# Compreensão de listas
df['Weight (kg)'] = [convertWeight(x) for x in df['Weight']]
df['Height (m)']  = [convertHeight(x) for x in df['Height']]

In [ ]:
colunas = ['Name', 'Team', 'Position', 'Age', 'Height', 'Height (m)', 'Weight', 'Weight (kg)', 'College', 'Salary']
df = df[colunas]

In [ ]:
df

,Name,Team,Position,Age,Height,Height (m),Weight,Weight (kg),College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,6-2,1.8796,180.0,81.646560,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,25.0,6-6,1.9812,235.0,106.594120,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,27.0,6-5,1.9558,205.0,92.986360,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,22.0,6-5,1.9558,185.0,83.914520,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,29.0,6-10,2.0828,231.0,104.779752,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,PF,20.0,6-10,2.0828,234.0,106.140528,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,PG,26.0,6-3,1.9050,203.0,92.079176,Butler,2433333.0
454,Raul Neto,Utah Jazz,PG,24.0,6-1,1.8542,179.0,81.192968,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,C,26.0,7-3,2.2098,256.0,116.119552,NaN,2900000.0
456,Jeff Withey,Utah Jazz,C,26.0,7-0,2.1336,231.0,104.779752,Kansas,947276.0

In [ ]:
# Groupby
grupos = df.groupby(by='Position')

In [ ]:
# Grupos
grupos.get_group('Kansas')['Salary'].mean()

np.float64(2861320.111111111)

In [ ]:
# Grupos
grupos['Salary'].max()

Position
C     22359364.0
PF    22192730.0
PG    21468695.0
SF    25000000.0
SG    20000000.0
Name: Salary, dtype: float64